const countries = [
    { dialCode: "+91", flag: "https://flagcdn.com/w40/in.png", alpha2: "IN", name: "India" },
    { dialCode: "+7", flag: "https://flagcdn.com/w40/ru.png", alpha2: "RU", name: "Russia" },
    { dialCode: "+7", flag: "https://flagcdn.com/w40/kz.png", alpha2: "KZ", name: "Kazakhstan" },
    { dialCode: "+81", flag: "https://flagcdn.com/w40/jp.png", alpha2: "JP", name: "Japan" },
    { dialCode: "+82", flag: "https://flagcdn.com/w40/kr.png", alpha2: "KR", name: "South Korea" },
    { dialCode: "+84", flag: "https://flagcdn.com/w40/vn.png", alpha2: "VN", name: "Vietnam" },
    { dialCode: "+850", flag: "https://flagcdn.com/w40/kp.png", alpha2: "KP", name: "North Korea" },
    { dialCode: "+852", flag: "https://flagcdn.com/w40/hk.png", alpha2: "HK", name: "Hong Kong" },
    { dialCode: "+853", flag: "https://flagcdn.com/w40/mo.png", alpha2: "MO", name: "Macau" },
    { dialCode: "+855", flag: "https://flagcdn.com/w40/kh.png", alpha2: "KH", name: "Cambodia" },
    { dialCode: "+856", flag: "https://flagcdn.com/w40/la.png", alpha2: "LA", name: "Laos" },
    { dialCode: "+86", flag: "https://flagcdn.com/w40/cn.png", alpha2: "CN", name: "China" },
    { dialCode: "+880", flag: "https://flagcdn.com/w40/bd.png", alpha2: "BD", name: "Bangladesh" },
    { dialCode: "+886", flag: "https://flagcdn.com/w40/tw.png", alpha2: "TW", name: "Taiwan" },
    { dialCode: "+90", flag: "https://flagcdn.com/w40/tr.png", alpha2: "TR", name: "Turkey" },
    { dialCode: "+92", flag: "https://flagcdn.com/w40/pk.png", alpha2: "PK", name: "Pakistan" },
    { dialCode: "+93", flag: "https://flagcdn.com/w40/af.png", alpha2: "AF", name: "Afghanistan" },
    { dialCode: "+94", flag: "https://flagcdn.com/w40/lk.png", alpha2: "LK", name: "Sri Lanka" },
    { dialCode: "+95", flag: "https://flagcdn.com/w40/mm.png", alpha2: "MM", name: "Myanmar" },
    { dialCode: "+960", flag: "https://flagcdn.com/w40/mv.png", alpha2: "MV", name: "Maldives" },
    { dialCode: "+1", flag: "https://flagcdn.com/w40/ca.png", alpha2: "CA", name: "Canada" },
    { dialCode: "+1", flag: "https://flagcdn.com/w40/us.png", alpha2: "US", name: "United States" },
    { dialCode: "+1242", flag: "https://flagcdn.com/w40/bs.png", alpha2: "BS", name: "Bahamas" },
    { dialCode: "+1246", flag: "https://flagcdn.com/w40/bb.png", alpha2: "BB", name: "Barbados" },
    { dialCode: "+1264", flag: "https://flagcdn.com/w40/ai.png", alpha2: "AI", name: "Anguilla" },
    { dialCode: "+1268", flag: "https://flagcdn.com/w40/ag.png", alpha2: "AG", name: "Antigua and Barbuda" },
    { dialCode: "+1284", flag: "https://flagcdn.com/w40/vg.png", alpha2: "VG", name: "Virgin Islands, British" },
    { dialCode: "+1340", flag: "https://flagcdn.com/w40/vi.png", alpha2: "VI", name: "Virgin Islands, U.S." },
    { dialCode: "+1441", flag: "https://flagcdn.com/w40/bm.png", alpha2: "BM", name: "Bermuda" },
    { dialCode: "+1473", flag: "https://flagcdn.com/w40/gd.png", alpha2: "GD", name: "Grenada" },
    { dialCode: "+1649", flag: "https://flagcdn.com/w40/tc.png", alpha2: "TC", name: "Turks and Caicos Islands" },
    { dialCode: "+1664", flag: "https://flagcdn.com/w40/ms.png", alpha2: "MS", name: "Montserrat" },
    { dialCode: "+1670", flag: "https://flagcdn.com/w40/mp.png", alpha2: "MP", name: "Northern Mariana Islands" },
    { dialCode: "+1671", flag: "https://flagcdn.com/w40/gu.png", alpha2: "GU", name: "Guam" },
    { dialCode: "+1684", flag: "https://flagcdn.com/w40/as.png", alpha2: "AS", name: "American Samoa" },
    { dialCode: "+1758", flag: "https://flagcdn.com/w40/lc.png", alpha2: "LC", name: "Saint Lucia" },
    { dialCode: "+1767", flag: "https://flagcdn.com/w40/dm.png", alpha2: "DM", name: "Dominica" },
    { dialCode: "+1784", flag: "https://flagcdn.com/w40/vc.png", alpha2: "VC", name: "Saint Vincent and the Grenadines" },
    { dialCode: "+1849", flag: "https://flagcdn.com/w40/do.png", alpha2: "DO", name: "Dominican Republic" },
    { dialCode: "+1868", flag: "https://flagcdn.com/w40/tt.png", alpha2: "TT", name: "Trinidad and Tobago" },
    { dialCode: "+1869", flag: "https://flagcdn.com/w40/kn.png", alpha2: "KN", name: "Saint Kitts and Nevis" },
    { dialCode: "+1876", flag: "https://flagcdn.com/w40/jm.png", alpha2: "JM", name: "Jamaica" },
    { dialCode: "+1939", flag: "https://flagcdn.com/w40/pr.png", alpha2: "PR", name: "Puerto Rico" },
    { dialCode: "+20", flag: "https://flagcdn.com/w40/eg.png", alpha2: "EG", name: "Egypt" },
    { dialCode: "+211", flag: "https://flagcdn.com/w40/ss.png", alpha2: "SS", name: "South Sudan" },
    { dialCode: "+212", flag: "https://flagcdn.com/w40/ma.png", alpha2: "MA", name: "Morocco" },
    { dialCode: "+213", flag: "https://flagcdn.com/w40/dz.png", alpha2: "DZ", name: "Algeria" },
    { dialCode: "+216", flag: "https://flagcdn.com/w40/tn.png", alpha2: "TN", name: "Tunisia" },
    { dialCode: "+218", flag: "https://flagcdn.com/w40/ly.png", alpha2: "LY", name: "Libya" },
    { dialCode: "+220", flag: "https://flagcdn.com/w40/gm.png", alpha2: "GM", name: "Gambia" },
    { dialCode: "+221", flag: "https://flagcdn.com/w40/sn.png", alpha2: "SN", name: "Senegal" },
    { dialCode: "+222", flag: "https://flagcdn.com/w40/mr.png", alpha2: "MR", name: "Mauritania" },
    { dialCode: "+223", flag: "https://flagcdn.com/w40/ml.png", alpha2: "ML", name: "Mali" },
    { dialCode: "+224", flag: "https://flagcdn.com/w40/gn.png", alpha2: "GN", name: "Guinea" },
    { dialCode: "+225", flag: "https://flagcdn.com/w40/ci.png", alpha2: "CI", name: "Cote d'Ivoire" },
    { dialCode: "+226", flag: "https://flagcdn.com/w40/bf.png", alpha2: "BF", name: "Burkina Faso" },
    { dialCode: "+227", flag: "https://flagcdn.com/w40/ne.png", alpha2: "NE", name: "Niger" },
    { dialCode: "+228", flag: "https://flagcdn.com/w40/tg.png", alpha2: "TG", name: "Togo" },
    { dialCode: "+229", flag: "https://flagcdn.com/w40/bj.png", alpha2: "BJ", name: "Benin" },
    { dialCode: "+230", flag: "https://flagcdn.com/w40/mu.png", alpha2: "MU", name: "Mauritius" },
    { dialCode: "+231", flag: "https://flagcdn.com/w40/lr.png", alpha2: "LR", name: "Liberia" },
    { dialCode: "+232", flag: "https://flagcdn.com/w40/sl.png", alpha2: "SL", name: "Sierra Leone" },
    { dialCode: "+233", flag: "https://flagcdn.com/w40/gh.png", alpha2: "GH", name: "Ghana" },
    { dialCode: "+234", flag: "https://flagcdn.com/w40/ng.png", alpha2: "NG", name: "Nigeria" },
    { dialCode: "+235", flag: "https://flagcdn.com/w40/td.png", alpha2: "TD", name: "Chad" },
    { dialCode: "+236", flag: "https://flagcdn.com/w40/cf.png", alpha2: "CF", name: "Central African Republic" },
    { dialCode: "+237", flag: "https://flagcdn.com/w40/cm.png", alpha2: "CM", name: "Cameroon" },
    { dialCode: "+238", flag: "https://flagcdn.com/w40/cv.png", alpha2: "CV", name: "Cape Verde" },
    { dialCode: "+239", flag: "https://flagcdn.com/w40/st.png", alpha2: "ST", name: "Sao Tome and Principe" },
    { dialCode: "+240", flag: "https://flagcdn.com/w40/gq.png", alpha2: "GQ", name: "Equatorial Guinea" },
    { dialCode: "+241", flag: "https://flagcdn.com/w40/ga.png", alpha2: "GA", name: "Gabon" },
    { dialCode: "+242", flag: "https://flagcdn.com/w40/cg.png", alpha2: "CG", name: "Congo" },
    { dialCode: "+243", flag: "https://flagcdn.com/w40/cd.png", alpha2: "CD", name: "Congo, The Democratic Republic of Congo" },
    { dialCode: "+244", flag: "https://flagcdn.com/w40/ao.png", alpha2: "AO", name: "Angola" },
    { dialCode: "+245", flag: "https://flagcdn.com/w40/gw.png", alpha2: "GW", name: "Guinea-Bissau" },
    { dialCode: "+246", flag: "https://flagcdn.com/w40/io.png", alpha2: "IO", name: "British Indian Ocean Territory" },
    { dialCode: "+248", flag: "https://flagcdn.com/w40/sc.png", alpha2: "SC", name: "Seychelles" },
    { dialCode: "+249", flag: "https://flagcdn.com/w40/sd.png", alpha2: "SD", name: "Sudan" },
    { dialCode: "+250", flag: "https://flagcdn.com/w40/rw.png", alpha2: "RW", name: "Rwanda" },
    { dialCode: "+251", flag: "https://flagcdn.com/w40/et.png", alpha2: "ET", name: "Ethiopia" },
    { dialCode: "+252", flag: "https://flagcdn.com/w40/so.png", alpha2: "SO", name: "Somalia" },
    { dialCode: "+253", flag: "https://flagcdn.com/w40/dj.png", alpha2: "DJ", name: "Djibouti" },
    { dialCode: "+254", flag: "https://flagcdn.com/w40/ke.png", alpha2: "KE", name: "Kenya" },
    { dialCode: "+255", flag: "https://flagcdn.com/w40/tz.png", alpha2: "TZ", name: "Tanzania, United Republic of Tanzania" },
    { dialCode: "+256", flag: "https://flagcdn.com/w40/ug.png", alpha2: "UG", name: "Uganda" },
    { dialCode: "+257", flag: "https://flagcdn.com/w40/bi.png", alpha2: "BI", name: "Burundi" },
    { dialCode: "+258", flag: "https://flagcdn.com/w40/mz.png", alpha2: "MZ", name: "Mozambique" },
    { dialCode: "+260", flag: "https://flagcdn.com/w40/zm.png", alpha2: "ZM", name: "Zambia" },
    { dialCode: "+261", flag: "https://flagcdn.com/w40/mg.png", alpha2: "MG", name: "Madagascar" },
    { dialCode: "+262", flag: "https://flagcdn.com/w40/yt.png", alpha2: "YT", name: "Mayotte" },
    { dialCode: "+262", flag: "https://flagcdn.com/w40/re.png", alpha2: "RE", name: "Reunion" },
    { dialCode: "+263", flag: "https://flagcdn.com/w40/zw.png", alpha2: "ZW", name: "Zimbabwe" },
    { dialCode: "+264", flag: "https://flagcdn.com/w40/na.png", alpha2: "NA", name: "Namibia" },
    { dialCode: "+265", flag: "https://flagcdn.com/w40/mw.png", alpha2: "MW", name: "Malawi" },
    { dialCode: "+266", flag: "https://flagcdn.com/w40/ls.png", alpha2: "LS", name: "Lesotho" },
    { dialCode: "+267", flag: "https://flagcdn.com/w40/bw.png", alpha2: "BW", name: "Botswana" },
    { dialCode: "+268", flag: "https://flagcdn.com/w40/sz.png", alpha2: "SZ", name: "Swaziland" },
    { dialCode: "+269", flag: "https://flagcdn.com/w40/km.png", alpha2: "KM", name: "Comoros" },
    { dialCode: "+27", flag: "https://flagcdn.com/w40/za.png", alpha2: "ZA", name: "South Africa" },
    { dialCode: "+290", flag: "https://flagcdn.com/w40/sh.png", alpha2: "SH", name: "Saint Helena" },
    { dialCode: "+291", flag: "https://flagcdn.com/w40/er.png", alpha2: "ER", name: "Eritrea" },
    { dialCode: "+297", flag: "https://flagcdn.com/w40/aw.png", alpha2: "AW", name: "Aruba" },
    { dialCode: "+298", flag: "https://flagcdn.com/w40/fo.png", alpha2: "FO", name: "Faroe Islands" },
    { dialCode: "+299", flag: "https://flagcdn.com/w40/gl.png", alpha2: "GL", name: "Greenland" },
    { dialCode: "+30", flag: "https://flagcdn.com/w40/gr.png", alpha2: "GR", name: "Greece" },
    { dialCode: "+31", flag: "https://flagcdn.com/w40/nl.png", alpha2: "NL", name: "Netherlands" },
    { dialCode: "+32", flag: "https://flagcdn.com/w40/be.png", alpha2: "BE", name: "Belgium" },
    { dialCode: "+33", flag: "https://flagcdn.com/w40/fr.png", alpha2: "FR", name: "France" },
    { dialCode: "+34", flag: "https://flagcdn.com/w40/es.png", alpha2: "ES", name: "Spain" },
    { dialCode: "+350", flag: "https://flagcdn.com/w40/gi.png", alpha2: "GI", name: "Gibraltar" },
    { dialCode: "+351", flag: "https://flagcdn.com/w40/pt.png", alpha2: "PT", name: "Portugal" },
    { dialCode: "+352", flag: "https://flagcdn.com/w40/lu.png", alpha2: "LU", name: "Luxembourg" },
    { dialCode: "+353", flag: "https://flagcdn.com/w40/ie.png", alpha2: "IE", name: "Ireland" },
    { dialCode: "+354", flag: "https://flagcdn.com/w40/is.png", alpha2: "IS", name: "Iceland" },
    { dialCode: "+355", flag: "https://flagcdn.com/w40/al.png", alpha2: "AL", name: "Albania" },
    { dialCode: "+356", flag: "https://flagcdn.com/w40/mt.png", alpha2: "MT", name: "Malta" },
    { dialCode: "+357", flag: "https://flagcdn.com/w40/cy.png", alpha2: "CY", name: "Cyprus" },
    { dialCode: "+358", flag: "https://flagcdn.com/w40/fi.png", alpha2: "FI", name: "Finland" },
    { dialCode: "+359", flag: "https://flagcdn.com/w40/bg.png", alpha2: "BG", name: "Bulgaria" },
    { dialCode: "+36", flag: "https://flagcdn.com/w40/hu.png", alpha2: "HU", name: "Hungary" },
    { dialCode: "+370", flag: "https://flagcdn.com/w40/lt.png", alpha2: "LT", name: "Lithuania" },
    { dialCode: "+371", flag: "https://flagcdn.com/w40/lv.png", alpha2: "LV", name: "Latvia" },
    { dialCode: "+372", flag: "https://flagcdn.com/w40/ee.png", alpha2: "EE", name: "Estonia" },
    { dialCode: "+373", flag: "https://flagcdn.com/w40/md.png", alpha2: "MD", name: "Moldova, Republic of Moldova" },
    { dialCode: "+374", flag: "https://flagcdn.com/w40/am.png", alpha2: "AM", name: "Armenia" },
    { dialCode: "+375", flag: "https://flagcdn.com/w40/by.png", alpha2: "BY", name: "Belarus" },
    { dialCode: "+376", flag: "https://flagcdn.com/w40/ad.png", alpha2: "AD", name: "Andorra" },
    { dialCode: "+377", flag: "https://flagcdn.com/w40/mc.png", alpha2: "MC", name: "Monaco" },
    { dialCode: "+378", flag: "https://flagcdn.com/w40/sm.png", alpha2: "SM", name: "San Marino" },
    { dialCode: "+380", flag: "https://flagcdn.com/w40/ua.png", alpha2: "UA", name: "Ukraine" },
    { dialCode: "+381", flag: "https://flagcdn.com/w40/rs.png", alpha2: "RS", name: "Serbia" },
    { dialCode: "+382", flag: "https://flagcdn.com/w40/me.png", alpha2: "ME", name: "Montenegro" },
    { dialCode: "+383", flag: "https://flagcdn.com/w40/xk.png", alpha2: "XK", name: "Kosovo" },
    { dialCode: "+385", flag: "https://flagcdn.com/w40/hr.png", alpha2: "HR", name: "Croatia" },
    { dialCode: "+386", flag: "https://flagcdn.com/w40/si.png", alpha2: "SI", name: "Slovenia" },
    { dialCode: "+387", flag: "https://flagcdn.com/w40/ba.png", alpha2: "BA", name: "Bosnia and Herzegovina" },
    { dialCode: "+389", flag: "https://flagcdn.com/w40/mk.png", alpha2: "MK", name: "North Macedonia" },
    { dialCode: "+39", flag: "https://flagcdn.com/w40/it.png", alpha2: "IT", name: "Italy" },
    { dialCode: "+40", flag: "https://flagcdn.com/w40/ro.png", alpha2: "RO", name: "Romania" },
    { dialCode: "+41", flag: "https://flagcdn.com/w40/ch.png", alpha2: "CH", name: "Switzerland" },
    { dialCode: "+420", flag: "https://flagcdn.com/w40/cz.png", alpha2: "CZ", name: "Czech Republic" },
    { dialCode: "+421", flag: "https://flagcdn.com/w40/sk.png", alpha2: "SK", name: "Slovakia" },
    { dialCode: "+423", flag: "https://flagcdn.com/w40/li.png", alpha2: "LI", name: "Liechtenstein" },
    { dialCode: "+43", flag: "https://flagcdn.com/w40/at.png", alpha2: "AT", name: "Austria" },
    { dialCode: "+44", flag: "https://flagcdn.com/w40/gb.png", alpha2: "GB", name: "United Kingdom" },
    { dialCode: "+45", flag: "https://flagcdn.com/w40/dk.png", alpha2: "DK", name: "Denmark" },
    { dialCode: "+46", flag: "https://flagcdn.com/w40/se.png", alpha2: "SE", name: "Sweden" },
    { dialCode: "+47", flag: "https://flagcdn.com/w40/no.png", alpha2: "NO", name: "Norway" },
    { dialCode: "+48", flag: "https://flagcdn.com/w40/pl.png", alpha2: "PL", name: "Poland" },
    { dialCode: "+49", flag: "https://flagcdn.com/w40/de.png", alpha2: "DE", name: "Germany" },
    { dialCode: "+500", flag: "https://flagcdn.com/w40/fk.png", alpha2: "FK", name: "Falkland Islands" },
    { dialCode: "+501", flag: "https://flagcdn.com/w40/bz.png", alpha2: "BZ", name: "Belize" },
    { dialCode: "+502", flag: "https://flagcdn.com/w40/gt.png", alpha2: "GT", name: "Guatemala" },
    { dialCode: "+503", flag: "https://flagcdn.com/w40/sv.png", alpha2: "SV", name: "El Salvador" },
    { dialCode: "+504", flag: "https://flagcdn.com/w40/hn.png", alpha2: "HN", name: "Honduras" },
    { dialCode: "+505", flag: "https://flagcdn.com/w40/ni.png", alpha2: "NI", name: "Nicaragua" },
    { dialCode: "+506", flag: "https://flagcdn.com/w40/cr.png", alpha2: "CR", name: "Costa Rica" },
    { dialCode: "+507", flag: "https://flagcdn.com/w40/pa.png", alpha2: "PA", name: "Panama" },
    { dialCode: "+508", flag: "https://flagcdn.com/w40/pm.png", alpha2: "PM", name: "Saint Pierre and Miquelon" },
    { dialCode: "+509", flag: "https://flagcdn.com/w40/ht.png", alpha2: "HT", name: "Haiti" },
    { dialCode: "+51", flag: "https://flagcdn.com/w40/pe.png", alpha2: "PE", name: "Peru" },
    { dialCode: "+52", flag: "https://flagcdn.com/w40/mx.png", alpha2: "MX", name: "Mexico" },
    { dialCode: "+53", flag: "https://flagcdn.com/w40/cu.png", alpha2: "CU", name: "Cuba" },
    { dialCode: "+54", flag: "https://flagcdn.com/w40/ar.png", alpha2: "AR", name: "Argentina" },
    { dialCode: "+55", flag: "https://flagcdn.com/w40/br.png", alpha2: "BR", name: "Brazil" },
    { dialCode: "+56", flag: "https://flagcdn.com/w40/cl.png", alpha2: "CL", name: "Chile" },
    { dialCode: "+57", flag: "https://flagcdn.com/w40/co.png", alpha2: "CO", name: "Colombia" },
    { dialCode: "+58", flag: "https://flagcdn.com/w40/ve.png", alpha2: "VE", name: "Venezuela, Bolivarian Republic of Venezuela" },
    { dialCode: "+590", flag: "https://flagcdn.com/w40/gp.png", alpha2: "GP", name: "Guadeloupe" },
    { dialCode: "+591", flag: "https://flagcdn.com/w40/bo.png", alpha2: "BO", name: "Bolivia" },
    { dialCode: "+592", flag: "https://flagcdn.com/w40/gy.png", alpha2: "GY", name: "Guyana" },
    { dialCode: "+593", flag: "https://flagcdn.com/w40/ec.png", alpha2: "EC", name: "Ecuador" },
    { dialCode: "+594", flag: "https://flagcdn.com/w40/gf.png", alpha2: "GF", name: "French Guiana" },
    { dialCode: "+595", flag: "https://flagcdn.com/w40/py.png", alpha2: "PY", name: "Paraguay" },
    { dialCode: "+596", flag: "https://flagcdn.com/w40/mq.png", alpha2: "MQ", name: "Martinique" },
    { dialCode: "+597", flag: "https://flagcdn.com/w40/sr.png", alpha2: "SR", name: "Suriname" },
    { dialCode: "+598", flag: "https://flagcdn.com/w40/uy.png", alpha2: "UY", name: "Uruguay" },
    { dialCode: "+599", flag: "https://flagcdn.com/w40/bq.png", alpha2: "BQ", name: "Bonaire, Sint Eustatius and Saba" },
    { dialCode: "+60", flag: "https://flagcdn.com/w40/my.png", alpha2: "MY", name: "Malaysia" },
    { dialCode: "+61", flag: "https://flagcdn.com/w40/au.png", alpha2: "AU", name: "Australia" },
    { dialCode: "+62", flag: "https://flagcdn.com/w40/id.png", alpha2: "ID", name: "Indonesia" },
    { dialCode: "+63", flag: "https://flagcdn.com/w40/ph.png", alpha2: "PH", name: "Philippines" },
    { dialCode: "+64", flag: "https://flagcdn.com/w40/nz.png", alpha2: "NZ", name: "New Zealand" },
    { dialCode: "+65", flag: "https://flagcdn.com/w40/sg.png", alpha2: "SG", name: "Singapore" },
    { dialCode: "+66", flag: "https://flagcdn.com/w40/th.png", alpha2: "TH", name: "Thailand" },
    { dialCode: "+670", flag: "https://flagcdn.com/w40/tl.png", alpha2: "TL", name: "Timor-Leste" },
    { dialCode: "+672", flag: "https://flagcdn.com/w40/nf.png", alpha2: "NF", name: "Norfolk Island" },
    { dialCode: "+673", flag: "https://flagcdn.com/w40/bn.png", alpha2: "BN", name: "Brunei Darussalam" },
    { dialCode: "+674", flag: "https://flagcdn.com/w40/nr.png", alpha2: "NR", name: "Nauru" },
    { dialCode: "+675", flag: "https://flagcdn.com/w40/pg.png", alpha2: "PG", name: "Papua New Guinea" },
    { dialCode: "+676", flag: "https://flagcdn.com/w40/to.png", alpha2: "TO", name: "Tonga" },
    { dialCode: "+677", flag: "https://flagcdn.com/w40/sb.png", alpha2: "SB", name: "Solomon Islands" },
    { dialCode: "+678", flag: "https://flagcdn.com/w40/vu.png", alpha2: "VU", name: "Vanuatu" },
    { dialCode: "+679", flag: "https://flagcdn.com/w40/fj.png", alpha2: "FJ", name: "Fiji" },
    { dialCode: "+680", flag: "https://flagcdn.com/w40/pw.png", alpha2: "PW", name: "Palau" },
    { dialCode: "+681", flag: "https://flagcdn.com/w40/wf.png", alpha2: "WF", name: "Wallis and Futuna" },
    { dialCode: "+682", flag: "https://flagcdn.com/w40/ck.png", alpha2: "CK", name: "Cook Islands" },
    { dialCode: "+683", flag: "https://flagcdn.com/w40/nu.png", alpha2: "NU", name: "Niue" },
    { dialCode: "+685", flag: "https://flagcdn.com/w40/ws.png", alpha2: "WS", name: "Samoa" },
    { dialCode: "+686", flag: "https://flagcdn.com/w40/ki.png", alpha2: "KI", name: "Kiribati" },
    { dialCode: "+687", flag: "https://flagcdn.com/w40/nc.png", alpha2: "NC", name: "New Caledonia" },
    { dialCode: "+688", flag: "https://flagcdn.com/w40/tv.png", alpha2: "TV", name: "Tuvalu" },
    { dialCode: "+689", flag: "https://flagcdn.com/w40/pf.png", alpha2: "PF", name: "French Polynesia" },
    { dialCode: "+690", flag: "https://flagcdn.com/w40/tk.png", alpha2: "TK", name: "Tokelau" },
    { dialCode: "+691", flag: "https://flagcdn.com/w40/fm.png", alpha2: "FM", name: "Micronesia, Federated States of Micronesia" },
    { dialCode: "+692", flag: "https://flagcdn.com/w40/mh.png", alpha2: "MH", name: "Marshall Islands" }
];

export default countries;
